//GENERATED BY cfg.py.

#ifndef _CFG_H_
#define _CFG_H_

struct cfg {
    int nr;
    int nc;
    int movement_increment;
    char* up;
    char* left;
    char* down;
    char* right;
    char* grid_keys;
    char* activation_key;
    char* close_key;
    char* buttons;
    char* trigger_mods;
    int hint_nc;
    int hint_nr;
    char* hint_mode;
    char* hint_up;
    char* hint_left;
    char* hint_down;
    char* hint_right;
    char* hint_bgcol;
    char* hint_fgcol;
    char* hint_characters;
    char* grid_col;
    char* grid_mouse_col;
    int grid_pointer_size;
    int grid_line_width;
    int grid_activation_timeout;
};

struct cfg* parse_cfg(const char *fname);

#endif
