/*
 * ---------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 * Original Author: Raheman Vaiya
 * ---------------------------------------------------------------------
 */

//GENERATED BY cfg.py

#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include "cfg.h"

static int kvp(char *line, char **key, char **val) {
  *key = NULL;
  *val = NULL;
  
  for(;*line != '\0';line++) {
    if(*line != ' ' && !*key)
      *key = line;
    
    if(*line == ':' && !*val) {
      *line++ = '\0';
      for(;isspace(*line);line++);
      *val = line;
    }
  }
  
  if(*(line - 1) == '\n')
    *(line - 1) = '\0';
  
  if(!(*val && *key))
    return -1;
  
  return 0;
}

struct cfg* parse_cfg(const char *fname) {
    char *line = NULL;
    size_t n = 0, ln = 0;
    struct cfg *cfg = malloc(sizeof(struct cfg));

    cfg->nr = 2;
    cfg->nc = 2;
    cfg->movement_increment = 20;
    cfg->up = "w";
    cfg->left = "a";
    cfg->down = "s";
    cfg->right = "d";
    cfg->grid_keys = "u,i,j,k";
    cfg->activation_key = "M-x";
    cfg->close_key = "Escape";
    cfg->button1 = "m";
    cfg->button2 = "comma";
    cfg->button3 = "period";
    cfg->trigger_mods = NULL;
    cfg->hint_nc = 20;
    cfg->hint_nr = 20;
    cfg->hint_mode = "false";
    cfg->hint_up = "k";
    cfg->hint_left = "h";
    cfg->hint_down = "j";
    cfg->hint_right = "l";

    FILE *fp = fopen(fname, "r");
    if(!fp) return cfg; //Return defaults if no config file xists..
    while(getline(&line, &n, fp) != -1) {
        ln++;
        char *key, *val;
        if(kvp(line, &key, &val)) {
            fprintf(stderr, "Invalid entry in %s at line %lu.\n", fname, ln);
            exit(1);
        }

        if(!strcmp(key, "nr"))
            cfg->nr = atoi(val);
        else if(!strcmp(key, "nc"))
            cfg->nc = atoi(val);
        else if(!strcmp(key, "movement_increment"))
            cfg->movement_increment = atoi(val);
        else if(!strcmp(key, "up"))
            cfg->up = strdup(val);
        else if(!strcmp(key, "left"))
            cfg->left = strdup(val);
        else if(!strcmp(key, "down"))
            cfg->down = strdup(val);
        else if(!strcmp(key, "right"))
            cfg->right = strdup(val);
        else if(!strcmp(key, "grid_keys"))
            cfg->grid_keys = strdup(val);
        else if(!strcmp(key, "activation_key"))
            cfg->activation_key = strdup(val);
        else if(!strcmp(key, "close_key"))
            cfg->close_key = strdup(val);
        else if(!strcmp(key, "button1"))
            cfg->button1 = strdup(val);
        else if(!strcmp(key, "button2"))
            cfg->button2 = strdup(val);
        else if(!strcmp(key, "button3"))
            cfg->button3 = strdup(val);
        else if(!strcmp(key, "trigger_mods"))
            cfg->trigger_mods = strdup(val);
        else if(!strcmp(key, "hint_nc"))
            cfg->hint_nc = atoi(val);
        else if(!strcmp(key, "hint_nr"))
            cfg->hint_nr = atoi(val);
        else if(!strcmp(key, "hint_mode"))
            cfg->hint_mode = strdup(val);
        else if(!strcmp(key, "hint_up"))
            cfg->hint_up = strdup(val);
        else if(!strcmp(key, "hint_left"))
            cfg->hint_left = strdup(val);
        else if(!strcmp(key, "hint_down"))
            cfg->hint_down = strdup(val);
        else if(!strcmp(key, "hint_right"))
            cfg->hint_right = strdup(val);

        free(line);
        line = NULL;
        n = 0;
    }

    return cfg;
}
